{% set name = "tf2onnx" %}
{% set version = "1.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/onnx/tensorflow-onnx/
  git_rev: v{{ version }}
  patches:
    - 0301-Updated-flatbuffers-to-be-1.12.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - python {{ python }}                    # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy {{ numpy }}                      # [build_platform != target_platform]
    - onnx {{ onnx }}
  host:
    - python {{ python }}
    - pip {{ pip }}
    - pytest-runner
    - numpy {{ numpy }}
    - requests {{ requests }}
    - six {{ six }}
  run:
    - python {{ python }}
    - onnx {{ onnx }}
    - {{ pin_compatible('numpy') }}
    - six {{ six }}
    - typing-extensions {{ typing_extensions }}  # [py<38]
    - requests {{ requests }}
    - python-flatbuffers {{ flatbuffers }}
    - tensorflow-base {{ tensorflow }}

test:
  commands:
    - python -m tf2onnx.convert --help

about:
  home: https://github.com/onnx/tensorflow-onnx
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tensorflow to ONNX converter
  description: tf2onnx - convert TensorFlow models to ONNX models.
  doc_url: http://simplejson.readthedocs.io/
  dev_url: https://github.com/onnx/tensorflow-onnx

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
